[Network]
topology = RailX2DHyperX
m_scale = 4
n_port = 2
internal_bandwidth = 4
external_latency = 10

[Workload]
traffic = uniform
# traffic = torus_all_reduce
# traffic = ring_all_reduce_bi
# traffic_scale = 16
# packet_length = 16

[Simulation]
injection_increment = 0.05
# threads = 8

[Files]
output_file = ../../output/railx_2D_hyperx.csv