[Network]
topology = RailX2DTorus
routing_algorithm = XY
m_scale = 2
n_port = 1
x_scale = 6
y_scale = 6
external_latency = 50

[Workload]
# traffic = uniform
traffic = collective_allreduce_torus

[Simulation]
injection_increment = 0.05 

[Files]
output_file = ../../output/railx_2D_torus.csv